// <auto-generated />
using System;
using GoalRoad.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalRoad.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoalRoad.Domain.Entities.CarreiraEntity", b =>
                {
                    b.Property<int>("IdCarreira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarreira"));

                    b.Property<string>("DescricaoCarreira")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("LogoCarreira")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TituloCarreira")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCarreira");

                    b.HasIndex("IdCategoria");

                    b.ToTable("GR_CARREIRA");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.CategoriaEntity", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("DescricaoCategoria")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("GR_CATEGORIA");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.FeedEntity", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("GR_FEED");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.FeedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("FonteId")
                        .HasColumnType("int");

                    b.Property<int?>("IdTecnologia")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<double>("Relevancia")
                        .HasColumnType("float");

                    b.Property<string>("TipoItem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdTecnologia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("GR_FEED_ITEM");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.LocalizacaoEntity", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEndereco");

                    b.ToTable("GR_ENDERECO");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.RoadMapEntity", b =>
                {
                    b.Property<int>("IdCarreira")
                        .HasColumnType("int");

                    b.HasKey("IdCarreira");

                    b.ToTable("GR_ROADMAP");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.RoadMapTecnologiaEntity", b =>
                {
                    b.Property<int>("IdRoadMap")
                        .HasColumnType("int");

                    b.Property<int>("IdTecnologia")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("IdRoadMap", "IdTecnologia");

                    b.HasIndex("IdTecnologia");

                    b.HasIndex("IdRoadMap", "StepOrder");

                    b.ToTable("GR_ROADMAP_TECNOLOGIA");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.TecnologiaEntity", b =>
                {
                    b.Property<int>("IdTecnologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTecnologia"));

                    b.Property<string>("DescricaoTecnologia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LogoTecnologia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeTecnologia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTecnologia");

                    b.ToTable("GR_TECNOLOGIA");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("CriadoEmUsuario")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEndereco")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEndereco")
                        .IsUnique()
                        .HasFilter("[IdEndereco] IS NOT NULL");

                    b.ToTable("GR_USUARIO");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.CarreiraEntity", b =>
                {
                    b.HasOne("GoalRoad.Domain.Entities.CategoriaEntity", "Categoria")
                        .WithMany("Carreiras")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.FeedEntity", b =>
                {
                    b.HasOne("GoalRoad.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithOne("Feed")
                        .HasForeignKey("GoalRoad.Domain.Entities.FeedEntity", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.FeedItemEntity", b =>
                {
                    b.HasOne("GoalRoad.Domain.Entities.TecnologiaEntity", "Tecnologia")
                        .WithMany("FeedItems")
                        .HasForeignKey("IdTecnologia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GoalRoad.Domain.Entities.FeedEntity", "Feed")
                        .WithMany("Items")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.RoadMapEntity", b =>
                {
                    b.HasOne("GoalRoad.Domain.Entities.CarreiraEntity", "Carreira")
                        .WithOne("RoadMap")
                        .HasForeignKey("GoalRoad.Domain.Entities.RoadMapEntity", "IdCarreira")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carreira");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.RoadMapTecnologiaEntity", b =>
                {
                    b.HasOne("GoalRoad.Domain.Entities.RoadMapEntity", "RoadMap")
                        .WithMany("Tecnologias")
                        .HasForeignKey("IdRoadMap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalRoad.Domain.Entities.TecnologiaEntity", "Tecnologia")
                        .WithMany()
                        .HasForeignKey("IdTecnologia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoadMap");

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.UsuarioEntity", b =>
                {
                    b.HasOne("GoalRoad.Domain.Entities.LocalizacaoEntity", "Localizacao")
                        .WithOne()
                        .HasForeignKey("GoalRoad.Domain.Entities.UsuarioEntity", "IdEndereco")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.CarreiraEntity", b =>
                {
                    b.Navigation("RoadMap");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.CategoriaEntity", b =>
                {
                    b.Navigation("Carreiras");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.FeedEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.RoadMapEntity", b =>
                {
                    b.Navigation("Tecnologias");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.TecnologiaEntity", b =>
                {
                    b.Navigation("FeedItems");
                });

            modelBuilder.Entity("GoalRoad.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Feed");
                });
#pragma warning restore 612, 618
        }
    }
}
